/**
 * @file Data models and schema definitions for the Smart Waste Management Platform.
 * Structured cleanly for zero-friction REST/WebSocket/GraphQL API integration.
 */

/**
 * @typedef {Object} CitizenReport
 * @property {string} id - Unique identifier (e.g. "REP-8492")
 * @property {string} category - "Overflowing Bin" | "Illegal Dumping" | "Missed Pickup" | "Hazardous Waste" | "Damaged Infrastructure"
 * @property {string} location - Address string or landmark description
 * @property {{ lat: number, lng: number }} [coordinates] - GPS coordinates
 * @property {string} description - Detailed citizen commentary
 * @property {string} [photoUrl] - Optional media attachment URL
 * @property {'Pending Verification' | 'Assigned' | 'In Progress' | 'Resolved'} status
 * @property {'Low' | 'Medium' | 'High' | 'Critical'} priority
 * @property {string} createdAt - ISO Timestamp
 * @property {string} [reporterName] - Optional citizen name or "Anonymous"
 */

/**
 * @typedef {Object} Vehicle
 * @property {string} id - Fleet ID (e.g. "WM-TRUCK-04")
 * @property {string} plateNumber - Registration plate
 * @property {string} driverName - Assigned operator name
 * @property {'Compactor' | 'Side-Loader' | 'Street Sweeper' | 'Hazardous Mini-Tipper'} type
 * @property {'Active' | 'Idle' | 'Maintenance' | 'Offline'} status
 * @property {string} lastLocation - Address or zone name
 * @property {{ lat: number, lng: number }} coordinates - Realtime telemetry GPS
 * @property {number} batteryOrFuel - Percentage 0-100
 * @property {number} loadCapacityPercent - Current bin payload percentage
 * @property {string} lastUpdated - ISO Timestamp
 */

/**
 * @typedef {Object} HotspotPrediction
 * @property {string} zoneId - Zone ID (e.g. "ZN-NORTH-02")
 * @property {string} zoneName - Descriptive Sector name
 * @property {'High' | 'Medium' | 'Low'} riskLevel - AI predicted overflow risk
 * @property {number} confidenceScore - Probability percentage 0-100%
 * @property {string} predictedVolume - Estimated waste surge volume (e.g., "3.4 Tons")
 * @property {string} primaryAnomaly - "Weekend Footfall Surge" | "Festival Overflow" | "Delayed Collection Cycle"
 * @property {{ lat: number, lng: number }} coordinates - Center centroid for heatmap
 * @property {string} suggestedAction - AI recommendation
 */

/**
 * @typedef {Object} RouteStop
 * @property {number} sequenceOrder - Order in optimized route (1, 2, 3...)
 * @property {string} stopName - Landmark or Street name
 * @property {string} binId - Monitored Smart Bin ID
 * @property {number} capacityPercent - Current IoT sensor fill level %
 * @property {string} estimatedArrival - Projected ETA time string
 * @property {{ lat: number, lng: number }} coordinates
 * @property {'Pending' | 'Serviced' | 'Skipped'} status
 */

/**
 * @typedef {Object} DashboardMetrics
 * @property {string|number} totalReports - Total citizen complaints logged
 * @property {string|number} activeVehicles - Active fleet units currently transmitting
 * @property {string|number} pendingIssues - Unresolved actionable issues
 * @property {string|number} predictedHotspots - High-risk zones identified by ML model
 */

export const EMPTY_DASHBOARD_METRICS = {
  totalReports: '—',
  activeVehicles: '—',
  pendingIssues: '—',
  predictedHotspots: '—',
};

export const DEFAULT_ML_HOTSPOTS = [
  {
    zoneId: 'HOTSPOT-AMD-01',
    zoneName: 'Manek Chowk Night Food Corridor',
    ward: 'Khadia / Central Zone (AMC)',
    riskLevel: 'High',
    confidenceScore: 95,
    predictedVolume: '5.2 Tons',
    primaryAnomaly: 'Late-night street food footfall + single-use disposables overflowing past 02:00 AM',
    suggestedAction: 'Schedule AMC Night Sweeper Unit & deploy 3x 1100L organic bins at King Gate',
    coordinates: { lat: 23.0248, lng: 72.5898 },
    radiusMeters: 400,
  },
  {
    zoneId: 'HOTSPOT-AMD-02',
    zoneName: 'Kalupur Ahmedabad Railway Terminal',
    ward: 'Kalupur / Central Zone (AMC)',
    riskLevel: 'High',
    confidenceScore: 93,
    predictedVolume: '4.8 Tons',
    primaryAnomaly: 'Inter-state transit passenger density + packaging discard near platform exits',
    suggestedAction: 'Increase compactor truck TRK-AMD-01 collection frequency to 4x daily',
    coordinates: { lat: 23.0232, lng: 72.6006 },
    radiusMeters: 450,
  },
  {
    zoneId: 'HOTSPOT-AMD-03',
    zoneName: 'Sindhu Bhavan Road (SBR) Commercial Strip',
    ward: 'Bodakdev / West Zone (AMC)',
    riskLevel: 'High',
    confidenceScore: 91,
    predictedVolume: '3.9 Tons',
    primaryAnomaly: 'Weekend dining & luxury retail packaging surge exceeding capacity by 190%',
    suggestedAction: 'Deploy automated hydraulic compactor at Pakwan Junction intersection',
    coordinates: { lat: 23.0451, lng: 72.5085 },
    radiusMeters: 450,
  },
  {
    zoneId: 'HOTSPOT-AMD-04',
    zoneName: 'Law Garden Khau Galli & Traditional Market',
    ward: 'Navrangpura / West Zone (AMC)',
    riskLevel: 'Medium',
    confidenceScore: 86,
    predictedVolume: '2.8 Tons',
    primaryAnomaly: 'Evening tourist footfall & beverage packaging spike between 18:00 - 23:00',
    suggestedAction: 'Install IoT level sensors & schedule specialized 22:00 clearing shift',
    coordinates: { lat: 23.0270, lng: 72.5596 },
    radiusMeters: 350,
  },
  {
    zoneId: 'HOTSPOT-AMD-05',
    zoneName: 'Naroda GIDC Industrial Estate & Chemical Belt',
    ward: 'Naroda / North Zone (AMC)',
    riskLevel: 'High',
    confidenceScore: 94,
    predictedVolume: '7.5 Tons',
    primaryAnomaly: 'Unauthorized industrial packaging & scrap dumping detected via GIS density clustering',
    suggestedAction: 'Dispatch AMC Hazardous Material Tipper & activate CCTV surveillance protocol',
    coordinates: { lat: 23.0725, lng: 72.6644 },
    radiusMeters: 600,
  },
  {
    zoneId: 'HOTSPOT-AMD-06',
    zoneName: 'Geeta Mandir Central ST Bus Terminal',
    ward: 'Astodia / South Zone (AMC)',
    riskLevel: 'High',
    confidenceScore: 89,
    predictedVolume: '4.1 Tons',
    primaryAnomaly: 'Continuous inter-district bus commuter volume + rapid roadside trash accumulation',
    suggestedAction: 'Reroute Fleet Truck TRK-AMD-03 for dedicated hourly transit sweeps',
    coordinates: { lat: 23.0135, lng: 72.5855 },
    radiusMeters: 400,
  },
  {
    zoneId: 'HOTSPOT-AMD-07',
    zoneName: 'CG Road Retail & Financial Corridor',
    ward: 'Navrangpura / West Zone (AMC)',
    riskLevel: 'Medium',
    confidenceScore: 79,
    predictedVolume: '2.6 Tons',
    primaryAnomaly: 'Commercial retail cardboard & packaging discard buildup near Panchvati Circle',
    suggestedAction: 'Mandate commercial recycling pickup windows between 14:00 - 16:00',
    coordinates: { lat: 23.0338, lng: 72.5607 },
    radiusMeters: 350,
  },
  {
    zoneId: 'HOTSPOT-AMD-08',
    zoneName: 'Vastrapur Lake Promenade & Food Street',
    ward: 'Vastrapur / West Zone (AMC)',
    riskLevel: 'Medium',
    confidenceScore: 82,
    predictedVolume: '3.3 Tons',
    primaryAnomaly: 'Weekend public park recreation & plastic bottle disposal overflow near lake entrance',
    suggestedAction: 'Position twin dual-stream recycling sorting hubs at South Gate',
    coordinates: { lat: 23.0350, lng: 72.5293 },
    radiusMeters: 400,
  },
  {
    zoneId: 'HOTSPOT-AMD-09',
    zoneName: 'SG Highway Gota-Vaishnodevi Junction',
    ward: 'Gota / North-West Zone (AMC)',
    riskLevel: 'Medium',
    confidenceScore: 77,
    predictedVolume: '5.0 Tons',
    primaryAnomaly: 'Rapid suburban construction debris & roadside dumping near highway service lanes',
    suggestedAction: 'Conduct daily mechanical street sweeper patrol and issue illegal dumping wardens',
    coordinates: { lat: 23.1147, lng: 72.5375 },
    radiusMeters: 550,
  },
  {
    zoneId: 'HOTSPOT-AMD-10',
    zoneName: 'Sabarmati Riverfront Promenade (Ellis Bridge)',
    ward: 'Paldi / Central Zone (AMC)',
    riskLevel: 'Low',
    confidenceScore: 72,
    predictedVolume: '1.9 Tons',
    primaryAnomaly: 'Evening promenade pedestrian footfall with seasonal food kiosk litter',
    suggestedAction: 'Deploy solar-powered self-compacting smart public bins every 200m',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    radiusMeters: 300,
  },
];

export const DEFAULT_DUSTBINS = [
  {
    id: 'BIN-AMD-101',
    name: 'Chandlodiya Garden Smart EcoBin',
    ward: 'Chandlodiya / North-West Zone',
    category: 'Dual Segregation (Wet & Dry)',
    fillLevel: 38,
    capacityLiters: 240,
    batteryLevel: 94,
    odourLevel: 'Low',
    status: 'Operational',
    lastEmptied: '2 hours ago',
    qrCode: 'SW-BIN-101',
    coordinates: { lat: 23.0784, lng: 72.5441 },
    acceptedWaste: ['Wet Organic', 'Dry Packaging', 'Plastic Bottles'],
  },
  {
    id: 'BIN-AMD-102',
    name: 'Vastrapur Lake Promenade Bin',
    ward: 'Vastrapur / West Zone',
    category: 'Smart Sensor (Wet / Organic)',
    fillLevel: 78,
    capacityLiters: 360,
    batteryLevel: 88,
    odourLevel: 'Normal',
    status: 'Moderate',
    lastEmptied: '4 hours ago',
    qrCode: 'SW-BIN-102',
    coordinates: { lat: 23.0350, lng: 72.5293 },
    acceptedWaste: ['Food Waste', 'Compostable Items', 'Wet Garbage'],
  },
  {
    id: 'BIN-AMD-103',
    name: 'Navrangpura Commerce Six Roads EcoHub',
    ward: 'Navrangpura / West Zone',
    category: 'Dry & Recyclable (Paper/Plastic)',
    fillLevel: 91,
    capacityLiters: 500,
    batteryLevel: 97,
    odourLevel: 'High',
    status: 'Full - Pickup Scheduled',
    lastEmptied: '8 hours ago',
    qrCode: 'SW-BIN-103',
    coordinates: { lat: 23.0373, lng: 72.5580 },
    acceptedWaste: ['Paper & Cardboard', 'Plastic & TetraPaks', 'Metal Cans'],
  },
  {
    id: 'BIN-AMD-104',
    name: 'Law Garden Street Food Waste Station',
    ward: 'Ellisbridge / Central Zone',
    category: 'Organic Food Waste Compactor',
    fillLevel: 84,
    capacityLiters: 600,
    batteryLevel: 91,
    odourLevel: 'High',
    status: 'Full - Pickup Scheduled',
    lastEmptied: '6 hours ago',
    qrCode: 'SW-BIN-104',
    coordinates: { lat: 23.0232, lng: 72.5601 },
    acceptedWaste: ['Street Food Scrap', 'Vegetable Waste', 'Biodegradable Plates'],
  },
  {
    id: 'BIN-AMD-105',
    name: 'Bodakdev Judges Bungalow Smart Hub',
    ward: 'Bodakdev / West Zone',
    category: 'Dual Segregation (Wet & Dry)',
    fillLevel: 22,
    capacityLiters: 240,
    batteryLevel: 99,
    odourLevel: 'Low',
    status: 'Operational',
    lastEmptied: '1 hour ago',
    qrCode: 'SW-BIN-105',
    coordinates: { lat: 23.0416, lng: 72.5112 },
    acceptedWaste: ['Household Wet Waste', 'Recyclable Dry Goods'],
  },
  {
    id: 'BIN-AMD-106',
    name: 'Satellite Shivranjani Crossroad E-Bin',
    ward: 'Satellite / South-West Zone',
    category: 'E-Waste & Hazardous Collection',
    fillLevel: 45,
    capacityLiters: 200,
    batteryLevel: 95,
    odourLevel: 'Low',
    status: 'Operational',
    lastEmptied: '1 day ago',
    qrCode: 'SW-BIN-106',
    coordinates: { lat: 23.0248, lng: 72.5291 },
    acceptedWaste: ['Batteries', 'Small Electronics', 'Cables & Bulbs'],
  },
  {
    id: 'BIN-AMD-107',
    name: 'Sabarmati Riverfront Walkway Bin #14',
    ward: 'Sabarmati / North Zone',
    category: 'Solar Powered Smart Compactor',
    fillLevel: 62,
    capacityLiters: 400,
    batteryLevel: 100,
    odourLevel: 'Low',
    status: 'Moderate',
    lastEmptied: '3 hours ago',
    qrCode: 'SW-BIN-107',
    coordinates: { lat: 23.0610, lng: 72.5830 },
    acceptedWaste: ['General Litter', 'Beverage Cups', 'Plastics'],
  },
  {
    id: 'BIN-AMD-108',
    name: 'Maninagar Kankaria Gate 3 EcoStation',
    ward: 'Maninagar / South Zone',
    category: 'Dual Segregation (Wet & Dry)',
    fillLevel: 89,
    capacityLiters: 500,
    batteryLevel: 82,
    odourLevel: 'High',
    status: 'Full - Pickup Scheduled',
    lastEmptied: '7 hours ago',
    qrCode: 'SW-BIN-108',
    coordinates: { lat: 22.9984, lng: 72.6022 },
    acceptedWaste: ['Food Waste', 'Packaging Wrappers', 'PET Bottles'],
  },
  {
    id: 'BIN-AMD-109',
    name: 'Bopal South Bopal Ring Road Bin',
    ward: 'Bopal / South-West Zone',
    category: 'Dry & Recyclable Plastic/Metal',
    fillLevel: 31,
    capacityLiters: 240,
    batteryLevel: 92,
    odourLevel: 'Low',
    status: 'Operational',
    lastEmptied: '3 hours ago',
    qrCode: 'SW-BIN-109',
    coordinates: { lat: 23.0298, lng: 72.4682 },
    acceptedWaste: ['Plastics', 'Cardboard', 'Aluminium Foil & Cans'],
  },
  {
    id: 'BIN-AMD-110',
    name: 'Gota Vandematram Circle Smart Hub',
    ward: 'Gota / North-West Zone',
    category: 'Dual Segregation (Wet & Dry)',
    fillLevel: 54,
    capacityLiters: 360,
    batteryLevel: 96,
    odourLevel: 'Normal',
    status: 'Moderate',
    lastEmptied: '5 hours ago',
    qrCode: 'SW-BIN-110',
    coordinates: { lat: 23.0945, lng: 72.5362 },
    acceptedWaste: ['Wet Organic', 'Domestic Dry Waste'],
  },
  {
    id: 'BIN-AMD-111',
    name: 'Prahlad Nagar Corporate Road EcoBin',
    ward: 'Prahlad Nagar / South-West Zone',
    category: 'E-Waste & Dry Recyclable',
    fillLevel: 19,
    capacityLiters: 240,
    batteryLevel: 98,
    odourLevel: 'Low',
    status: 'Operational',
    lastEmptied: '30 mins ago',
    qrCode: 'SW-BIN-111',
    coordinates: { lat: 23.0086, lng: 72.5074 },
    acceptedWaste: ['Office Paper', 'Electronic Accessories', 'Cartridges'],
  },
  {
    id: 'BIN-AMD-112',
    name: 'SG Highway Iscon Crossroad Smart Station',
    ward: 'SG Highway / West Zone',
    category: 'Solar Powered Smart Compactor',
    fillLevel: 73,
    capacityLiters: 600,
    batteryLevel: 89,
    odourLevel: 'Normal',
    status: 'Moderate',
    lastEmptied: '4 hours ago',
    qrCode: 'SW-BIN-112',
    coordinates: { lat: 23.0287, lng: 72.5069 },
    acceptedWaste: ['High-volume Commercial Waste', 'Plastics', 'Food Containers'],
  },
];

export const DEFAULT_AHMEDABAD_VEHICLES = [
  {
    id: 'TRK-AMD-801',
    plateNumber: 'GJ-01-CZ-4821',
    driverName: 'Suresh Kumar',
    driverPhone: '9823144552',
    driverBadge: 'DRV-801',
    driverEmail: 'suresh.k@wastefleet.org',
    driverPin: 'FLT-801-AUTH',
    type: 'Heavy Compactor (14T)',
    status: 'Active',
    lastLocation: 'Chandlodiya Garden - Sector 14 North Junction, Ahmedabad',
    coordinates: { lat: 23.0784, lng: 72.5441 },
    speed: 24,
    heading: 'NE',
    batteryOrFuel: 85,
    loadCapacityPercent: 68,
    assignedRoute: 'Route A1 - North Ahmedabad (Chandlodiya - Ranip - RTO Circle)',
    lastUpdated: '1 min ago',
  },
  {
    id: 'TRK-AMD-802',
    plateNumber: 'GJ-01-EV-1234',
    driverName: 'Ramesh Patel',
    driverPhone: '9825011223',
    driverBadge: 'DRV-802',
    driverEmail: 'ramesh.patel@wastefleet.org',
    driverPin: 'FLT-802-AUTH',
    type: 'Electric Tipper (4.5T)',
    status: 'Active',
    lastLocation: 'Satellite Shivranjani Cross Road, Ahmedabad',
    coordinates: { lat: 23.0225, lng: 72.5280 },
    speed: 18,
    heading: 'SW',
    batteryOrFuel: 92,
    loadCapacityPercent: 42,
    assignedRoute: 'Route W2 - Western Commercial (Satellite - Vastrapur - IIM-A)',
    lastUpdated: 'Just now',
  },
  {
    id: 'TRK-AMD-803',
    plateNumber: 'GJ-27-AK-5678',
    driverName: 'Vikram Singh',
    driverPhone: '9876501234',
    driverBadge: 'DRV-803',
    driverEmail: 'vikram.singh@wastefleet.org',
    driverPin: 'FLT-803-AUTH',
    type: 'Rear-Loader Compactor (10T)',
    status: 'Active',
    lastLocation: 'Sindhu Bhavan Road (SBR) & Pakwan Junction, Ahmedabad',
    coordinates: { lat: 23.0451, lng: 72.5085 },
    speed: 31,
    heading: 'E',
    batteryOrFuel: 76,
    loadCapacityPercent: 88,
    assignedRoute: 'Route W4 - SG Highway & Thaltej Expressway Corridor',
    lastUpdated: '2 mins ago',
  },
  {
    id: 'TRK-AMD-804',
    plateNumber: 'GJ-01-BQ-9012',
    driverName: 'Mahesh Sharma',
    driverPhone: '9898012345',
    driverBadge: 'DRV-804',
    driverEmail: 'mahesh.sharma@wastefleet.org',
    driverPin: 'FLT-804-AUTH',
    type: 'Hook-Loader Bin Carrier (12T)',
    status: 'Active',
    lastLocation: 'Manek Chowk & Khadia Heritage Corridor, Ahmedabad',
    coordinates: { lat: 23.0248, lng: 72.5898 },
    speed: 14,
    heading: 'N',
    batteryOrFuel: 68,
    loadCapacityPercent: 91,
    assignedRoute: 'Route C1 - Walled City Heritage & Night Market Route',
    lastUpdated: '4 mins ago',
  },
  {
    id: 'TRK-AMD-805',
    plateNumber: 'GJ-01-DW-3456',
    driverName: 'Rajesh Yadav',
    driverPhone: '9812345678',
    driverBadge: 'DRV-805',
    driverEmail: 'rajesh.yadav@wastefleet.org',
    driverPin: 'FLT-805-AUTH',
    type: 'Mini Bio-Waste Collector (2.5T)',
    status: 'Active',
    lastLocation: 'Civil Hospital & Asarwa Health Zone, Ahmedabad',
    coordinates: { lat: 23.0538, lng: 72.5975 },
    speed: 20,
    heading: 'NW',
    batteryOrFuel: 80,
    loadCapacityPercent: 55,
    assignedRoute: 'Route N3 - Asarwa Hospital & Bio-Medical Specialized Corridor',
    lastUpdated: '1 min ago',
  },
  {
    id: 'TRK-AMD-806',
    plateNumber: 'GJ-01-HY-7890',
    driverName: 'Dharmesh Solanki',
    driverPhone: '9824056789',
    driverBadge: 'DRV-806',
    driverEmail: 'dharmesh.solanki@wastefleet.org',
    driverPin: 'FLT-806-AUTH',
    type: 'Mechanical Street Sweeper',
    status: 'Active',
    lastLocation: 'Kankaria Lake Front Gate 3 - Maninagar, Ahmedabad',
    coordinates: { lat: 23.0063, lng: 72.6025 },
    speed: 12,
    heading: 'SE',
    batteryOrFuel: 88,
    loadCapacityPercent: 35,
    assignedRoute: 'Route S1 - South Ahmedabad (Maninagar - Kankaria - Isanpur)',
    lastUpdated: '3 mins ago',
  },
  {
    id: 'TRK-AMD-807',
    plateNumber: 'GJ-01-KL-2468',
    driverName: 'Pravin Parmar',
    driverPhone: '9898123456',
    driverBadge: 'DRV-807',
    driverEmail: 'pravin.parmar@wastefleet.org',
    driverPin: 'FLT-807-AUTH',
    type: 'Side-Loader Eco Collector (8T)',
    status: 'Idle',
    lastLocation: 'Law Garden Khau Galli & Ellisbridge, Ahmedabad',
    coordinates: { lat: 23.0270, lng: 72.5596 },
    speed: 0,
    heading: 'W',
    batteryOrFuel: 95,
    loadCapacityPercent: 15,
    assignedRoute: 'Route C3 - Navrangpura & Ashram Road Riverfront Zone',
    lastUpdated: '5 mins ago',
  },
  {
    id: 'TRK-AMD-808',
    plateNumber: 'GJ-27-MN-1357',
    driverName: 'Jignesh Vaghela',
    driverPhone: '9825678901',
    driverBadge: 'DRV-808',
    driverEmail: 'jignesh.vaghela@wastefleet.org',
    driverPin: 'FLT-808-AUTH',
    type: 'Heavy Compactor (14T)',
    status: 'Active',
    lastLocation: 'South Bopal Ring Road & Shilaj Junction, Ahmedabad',
    coordinates: { lat: 23.0335, lng: 72.4640 },
    speed: 28,
    heading: 'NW',
    batteryOrFuel: 83,
    loadCapacityPercent: 62,
    assignedRoute: 'Route W5 - Bopal & Ghuma West Residential Sector',
    lastUpdated: '2 mins ago',
  },
  {
    id: 'TRK-AMD-809',
    plateNumber: 'GJ-01-PR-9753',
    driverName: 'Chetan Barot',
    driverPhone: '9879012345',
    driverBadge: 'DRV-809',
    driverEmail: 'chetan.barot@wastefleet.org',
    driverPin: 'FLT-809-AUTH',
    type: 'Hazardous Waste Tipper (10T)',
    status: 'Maintenance',
    lastLocation: 'Naroda GIDC Industrial Estate Phase 2, Ahmedabad',
    coordinates: { lat: 23.0760, lng: 72.6580 },
    speed: 0,
    heading: 'NE',
    batteryOrFuel: 60,
    loadCapacityPercent: 0,
    assignedRoute: 'Route E2 - East Ahmedabad Industrial (Naroda - Odhav - Nikol)',
    lastUpdated: '10 mins ago',
  },
  {
    id: 'TRK-AMD-810',
    plateNumber: 'GJ-01-TX-8642',
    driverName: 'Ketan Makwana',
    driverPhone: '9825123499',
    driverBadge: 'DRV-810',
    driverEmail: 'ketan.makwana@wastefleet.org',
    driverPin: 'FLT-810-AUTH',
    type: 'Zero-Emission Electric Sweeper',
    status: 'Active',
    lastLocation: 'Sabarmati Riverfront Promenade West, Ahmedabad',
    coordinates: { lat: 23.0390, lng: 72.5710 },
    speed: 15,
    heading: 'S',
    batteryOrFuel: 91,
    loadCapacityPercent: 28,
    assignedRoute: 'Route R1 - Sabarmati Riverfront Green Corridor',
    lastUpdated: 'Just now',
  },
];

export const DEFAULT_AHMEDABAD_REPORTS = [
  {
    id: 'REP-AMD-501',
    category: 'Commercial Dumpster Overflow',
    priority: 'Critical',
    location: 'Near Law Garden Food Street, Ellis Bridge',
    ward: 'Ward 8 (Ellis Bridge & Law Garden)',
    description: 'Food packaging crates and heavy organic waste overflowing behind street market stalls.',
    citizen_name: 'Pooja Trivedi',
    citizen_phone: '+91 98251 66723',
    status: 'Pending Verification',
    latitude: 23.0232,
    longitude: 72.5574,
    coordinates: { lat: 23.0232, lng: 72.5574 },
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-807',
  },
  {
    id: 'REP-AMD-502',
    category: 'Illegal Construction Rubble',
    priority: 'High',
    location: 'Science City Road near CIMS Circle, Sola',
    ward: 'Ward 18 (Sola & Science City)',
    description: 'Masonry rubble and concrete bags dumped on public pedestrian footpath.',
    citizen_name: 'Aniket Sharma',
    citizen_phone: '+91 98790 44312',
    status: 'Pending Verification',
    latitude: 23.0725,
    longitude: 72.5180,
    coordinates: { lat: 23.0725, lng: 72.5180 },
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-803',
  },
  {
    id: 'REP-AMD-503',
    category: 'Plastic Waste & Litter',
    priority: 'Medium',
    location: 'Kankaria Lakefront Gate No. 4, Maninagar',
    ward: 'Ward 24 (Maninagar South)',
    description: 'Discarded beverage plastic bottles and snack wrappers accumulating near park benches.',
    citizen_name: 'Meera Solanki',
    citizen_phone: '+91 98982 11987',
    status: 'Pending Verification',
    latitude: 23.0068,
    longitude: 72.6021,
    coordinates: { lat: 23.0068, lng: 72.6021 },
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-806',
  },
  {
    id: 'REP-AMD-504',
    category: 'Vegetable Market Residue',
    priority: 'Critical',
    location: 'Kalupur Wholesale Market Outer Gate',
    ward: 'Ward 3 (Kalupur & Relief Road)',
    description: 'Decaying organic vegetable peelings blocking market entry drain.',
    citizen_name: 'Rajesh Vora',
    citizen_phone: '+91 98242 88412',
    status: 'Pending Verification',
    latitude: 23.0298,
    longitude: 72.5985,
    coordinates: { lat: 23.0298, lng: 72.5985 },
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-804',
  },
  {
    id: 'REP-AMD-505',
    category: 'Industrial Carton & Pallet Dump',
    priority: 'High',
    location: 'Naroda GIDC Phase 3 Main Avenue',
    ward: 'Ward 30 (Naroda Industrial)',
    description: 'Heavy cardboard packaging scrap and strapped wooden pallets dumped on road shoulder.',
    citizen_name: 'Hitesh Panchal',
    citizen_phone: '+91 98255 12093',
    status: 'Pending Verification',
    latitude: 23.0684,
    longitude: 72.6582,
    coordinates: { lat: 23.0684, lng: 72.6582 },
    created_at: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-809',
  },
  {
    id: 'REP-AMD-506',
    category: 'Green Garden Refuse Pile',
    priority: 'Medium',
    location: 'South Bopal Ring Road Junction',
    ward: 'Ward 21 (South Bopal & Ghuma)',
    description: 'Pruned garden branches and dry leaves piled up adjacent to society gate.',
    citizen_name: 'Kavita Patel',
    citizen_phone: '+91 98795 33201',
    status: 'Pending Verification',
    latitude: 23.0310,
    longitude: 72.4645,
    coordinates: { lat: 23.0310, lng: 72.4645 },
    created_at: new Date(Date.now() - 160 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-808',
  },
  {
    id: 'REP-AMD-507',
    category: 'Public Smart Bin Jammed',
    priority: 'Critical',
    location: 'Chandlodiya Railway Station West Cross',
    ward: 'Ward 14 (Chandlodiya & Ranip)',
    description: 'Bin sensor full alarm ringing, flap mechanism stuck with oversized cardboard container.',
    citizen_name: 'Dharmesh Joshi',
    citizen_phone: '+91 98250 99451',
    status: 'Pending Verification',
    latitude: 23.0825,
    longitude: 72.5440,
    coordinates: { lat: 23.0825, lng: 72.5440 },
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-801',
  },
  {
    id: 'REP-AMD-508',
    category: 'Biomedical Outer Box Disposal',
    priority: 'Critical',
    location: 'Near Asarwa Civil Hospital Gate 7',
    ward: 'Ward 16 (Asarwa & Civil)',
    description: 'Discarded clinic supplies packing boxes and PPE cartons stacked near compound wall.',
    citizen_name: 'Dr. Sameer Kadri',
    citizen_phone: '+91 98244 55120',
    status: 'Pending Verification',
    latitude: 23.0542,
    longitude: 72.6030,
    coordinates: { lat: 23.0542, lng: 72.6030 },
    created_at: new Date(Date.now() - 210 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-805',
  },
  {
    id: 'REP-AMD-509',
    category: 'Night Food Hub Container Spill',
    priority: 'High',
    location: 'Sindhu Bhavan Road Food Street',
    ward: 'Ward 10 (Bodakdev & SBR)',
    description: 'Beverage cups, disposable paper cartons, and foil packaging scattered on median.',
    citizen_name: 'Varun Nair',
    citizen_phone: '+91 99090 77812',
    status: 'Pending Verification',
    latitude: 23.0478,
    longitude: 72.5088,
    coordinates: { lat: 23.0478, lng: 72.5088 },
    created_at: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-803',
  },
  {
    id: 'REP-AMD-510',
    category: 'Riverfront Promenade Bin Overflow',
    priority: 'High',
    location: 'Sabarmati Riverfront Walkway near Subhash Bridge',
    ward: 'Ward 12 (Sabarmati & Riverfront North)',
    description: 'Public dustbins full along walking track with tourist waste spilling onto river bank.',
    citizen_name: 'Tanvi Adani',
    citizen_phone: '+91 98988 66234',
    status: 'Pending Verification',
    latitude: 23.0610,
    longitude: 72.5780,
    coordinates: { lat: 23.0610, lng: 72.5780 },
    created_at: new Date(Date.now() - 270 * 60 * 1000).toISOString(),
    assigned_driver: 'TRK-AMD-810',
  },
];


